

obstacle_range: 3.0
raytrace_range: 3.5

robot_radius: 0.20

inflation_radius: 0.22
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: kinect_scan, marking: true, clearing: true}
